-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 16:18:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS ATM;
CREATE DATABASE IF NOT EXISTS ATM;
USE ATM;
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `User_id` INT NOT NULL,
  `User_name` VARCHAR(45) NOT NULL,
  `dob` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank` ;

CREATE TABLE IF NOT EXISTS `Bank` (
  `Bank_id` INT NOT NULL,
  `Bank_name` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  PRIMARY KEY (`Bank_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM` ;

CREATE TABLE IF NOT EXISTS `ATM` (
  `ATM_id` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Bank` INT NOT NULL,
  PRIMARY KEY (`ATM_id`, `Bank`),
  INDEX `FK_ATM_Bank_idx` (`Bank` ASC) VISIBLE,
  CONSTRAINT `FK_ATM_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `Accounts_id` INT NOT NULL,
  `Bank` INT NOT NULL,
  `User` INT NOT NULL,
  `time` TIMESTAMP(6) NULL,
  `Location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Accounts_id`),
  INDEX `FK_user_ATM_idx` (`Bank` ASC) VISIBLE,
  INDEX `FK_Account_User_idx` (`User` ASC) VISIBLE,
  CONSTRAINT `FK_Accout_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Account_User`
    FOREIGN KEY (`User`)
    REFERENCES `User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transactions` ;

CREATE TABLE IF NOT EXISTS `Transactions` (
  `Transactions_id` INT NOT NULL,
  `User` INT NOT NULL,
  `time` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`Transactions_id`),
  INDEX `FK_Transactions_User_idx` (`User` ASC) VISIBLE,
  CONSTRAINT `FK_Transactions_User`
    FOREIGN KEY (`User`)
    REFERENCES `User` (`User_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Maintenance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Maintenance` ;

CREATE TABLE IF NOT EXISTS `Maintenance` (
  `Maintenance_id` INT NOT NULL,
  `Bank` INT NOT NULL,
  `ATM` INT NOT NULL,
  `employee` INT NOT NULL,
  `Location` VARCHAR(45) NULL,
  `time` TIMESTAMP(6) NULL,
  PRIMARY KEY (`Maintenance_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reports` ;

CREATE TABLE IF NOT EXISTS `Reports` (
  `Report_id` INT NOT NULL,
  `Bank` INT NOT NULL,
  `ATM` INT NOT NULL,
  `time` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`Report_id`),
  INDEX `FK_Reports_Bank_idx` (`Bank` ASC) VISIBLE,
  INDEX `FK_Reports_ATM_idx` (`ATM` ASC) VISIBLE,
  CONSTRAINT `FK_Reports_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Reports_ATM`
    FOREIGN KEY (`ATM`)
    REFERENCES `ATM` (`ATM_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer_Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer_Service` ;

CREATE TABLE IF NOT EXISTS `Customer_Service` (
  `Customer_Service_id` INT NOT NULL,
  `Bank` INT NOT NULL,
  `User` INT NOT NULL,
  `time` TIMESTAMP(6) NULL,
  PRIMARY KEY (`Customer_Service_id`),
  INDEX `FK_Customer_Service_Maintenance_idx` (`Bank` ASC) VISIBLE,
  INDEX `FK_Customer_Service_User_idx` (`User` ASC) VISIBLE,
  CONSTRAINT `FK_Customer_Service_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Customer_Service_User`
    FOREIGN KEY (`User`)
    REFERENCES `User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Security_Code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Security_Code` ;

CREATE TABLE IF NOT EXISTS `Security_Code` (
  `Security_Code_id` INT NOT NULL,
  `Accounts` INT NULL,
  `User` INT NULL,
  PRIMARY KEY (`Security_Code_id`),
  INDEX `FK_Security_Code_User_idx` (`User` ASC) VISIBLE,
  INDEX `FK_Security_Code_Bank_idx` (`Accounts` ASC) VISIBLE,
  CONSTRAINT `FK_Security_Code_Account`
    FOREIGN KEY (`Accounts`)
    REFERENCES `Account` (`Accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Security_Code_User`
    FOREIGN KEY (`User`)
    REFERENCES `User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cash_Dispenser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cash_Dispenser` ;

CREATE TABLE IF NOT EXISTS `Cash_Dispenser` (
  `Cash_Dispenser_id` INT NOT NULL,
  `Bank` INT NULL,
  `ATM` INT NULL,
  `time` TIMESTAMP(6) NULL,
  PRIMARY KEY (`Cash_Dispenser_id`),
  INDEX `FK_Cash_Dispenser_ATM_idx` (`ATM` ASC) VISIBLE,
  CONSTRAINT `FK_Cash_Dispenser_ATM`
    FOREIGN KEY (`ATM`)
    REFERENCES `ATM` (`ATM_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '					';


-- -----------------------------------------------------
-- Table `Depository_Modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Depository_Modules` ;

CREATE TABLE IF NOT EXISTS `Depository_Modules` (
  `Depository_Modules_id` INT NOT NULL,
  `Bank` INT NULL,
  `ATM` INT NULL,
  `Maintenance` INT NULL,
  PRIMARY KEY (`Depository_Modules_id`),
  INDEX `FK_Depository_Modules_idx` (`ATM` ASC) VISIBLE,
  CONSTRAINT `FK_Depository_Modules`
    FOREIGN KEY (`ATM`)
    REFERENCES `ATM` (`ATM_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Card_Reader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Card_Reader` ;

CREATE TABLE IF NOT EXISTS `Card_Reader` (
  `Card_Reader_id` INT NOT NULL,
  `Bank` INT NOT NULL,
  `ATM` INT NOT NULL,
  `Maintenance` INT NOT NULL,
  PRIMARY KEY (`Card_Reader_id`),
  INDEX `FK_Card_Reader_Bank_idx` (`Bank` ASC) VISIBLE,
  INDEX `FK_Card_Reader_ATM_idx` (`ATM` ASC) VISIBLE,
  CONSTRAINT `FK_Card_Reader_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Card_Reader_ATM`
    FOREIGN KEY (`ATM`)
    REFERENCES `ATM` (`ATM_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Receipt_Printers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receipt_Printers` ;

CREATE TABLE IF NOT EXISTS `Receipt_Printers` (
  `Receipt_Printers_id` INT NOT NULL,
  `Receipt_count` INT NULL,
  `Bank` INT NULL,
  `ATM` INT NULL,
  `Maintenance` INT NULL,
  PRIMARY KEY (`Receipt_Printers_id`),
  INDEX `FK_Receipt_Printers_Maintenance_idx` (`Maintenance` ASC) VISIBLE,
  CONSTRAINT `FK_Receipt_Printers_Maintenance`
    FOREIGN KEY (`Maintenance`)
    REFERENCES `Maintenance` (`Maintenance_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Region` ;

CREATE TABLE IF NOT EXISTS `Region` (
  `Region_id` INT NOT NULL,
  `ATM` INT NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Region_id`),
  INDEX `FK_Region_ATM_idx` (`ATM` ASC) VISIBLE,
  CONSTRAINT `FK_Region_ATM`
    FOREIGN KEY (`ATM`)
    REFERENCES `ATM` (`ATM_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `Employee_id` INT NOT NULL,
  `Bank` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `dob` TIMESTAMP(6) NOT NULL,
  `manager` INT NOT NULL,
  PRIMARY KEY (`Employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Roles` ;

CREATE TABLE IF NOT EXISTS `Roles` (
  `Roles_id` INT NOT NULL,
  `Bank` INT NOT NULL,
  `Employee` INT NOT NULL,
  `Assigned` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Roles_id`),
  INDEX `FK_Roles_Bank_idx` (`Bank` ASC) VISIBLE,
  CONSTRAINT `FK_Roles_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `View_Balance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `View_Balance` ;

CREATE TABLE IF NOT EXISTS `View_Balance` (
  `View_id` INT NOT NULL,
  `Account` INT NULL,
  `bank` INT NULL,
  `time` TIMESTAMP(6) NULL,
  PRIMARY KEY (`View_id`),
  INDEX `FK_View_Balance_Account_idx` (`Account` ASC) VISIBLE,
  INDEX `FK_View_Balance_Bank_idx` (`bank` ASC) VISIBLE,
  CONSTRAINT `FK_View_Balance_Bank`
    FOREIGN KEY (`bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_View_Balance_Account`
    FOREIGN KEY (`Account`)
    REFERENCES `Account` (`Accounts_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Access` ;

CREATE TABLE IF NOT EXISTS `Access` (
  `Access_id` INT NOT NULL,
  `User` INT NOT NULL,
  `ATM_id` INT NOT NULL,
  `time` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`Access_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Personal_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Personal_Details` ;

CREATE TABLE IF NOT EXISTS `Personal_Details` (
  `Personal_Details_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `dob` TIMESTAMP(6) NOT NULL,
  `sur_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Personal_Details_id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `Feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Feedback` ;

CREATE TABLE IF NOT EXISTS `Feedback` (
  `feedback_id` INT NOT NULL,
  `User` INT NOT NULL,
  `Account` INT NOT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `FK_Feedback_User_idx` (`User` ASC) VISIBLE,
  CONSTRAINT `FK_Feedback_User`
    FOREIGN KEY (`User`)
    REFERENCES `User` (`User_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `Payment_id` INT NOT NULL,
  `Employee` INT NOT NULL,
  `Bank` INT NOT NULL,
  PRIMARY KEY (`Payment_id`),
  INDEX `FK_Payment_Emloyee_idx` (`Employee` ASC) VISIBLE,
  INDEX `FK_Payment_Bank_idx` (`Bank` ASC) VISIBLE,
  CONSTRAINT `FK_Payment_Emloyee`
    FOREIGN KEY (`Employee`)
    REFERENCES `Employee` (`Employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Payment_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Monitor` ;

CREATE TABLE IF NOT EXISTS `Monitor` (
  `Check_id` INT NOT NULL,
  `Maintenainance` INT NOT NULL,
  `Card_Reader` INT NOT NULL,
  `Depository_Module` INT NOT NULL,
  PRIMARY KEY (`Check_id`),
  INDEX `FK_Check_Cad_Reader_idx` (`Card_Reader` ASC) VISIBLE,
  INDEX `FK_Check_Depository_module_idx` (`Depository_Module` ASC) VISIBLE,
  INDEX `FK_Check_Maintenaince_idx` (`Maintenainance` ASC) VISIBLE,
  CONSTRAINT `FK_Monitor_Maintenaince`
    FOREIGN KEY (`Maintenainance`)
    REFERENCES `Maintenance` (`Maintenance_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Monitor_Cad_Reader`
    FOREIGN KEY (`Card_Reader`)
    REFERENCES `Card_Reader` (`Card_Reader_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Monitor_Depository_module`
    FOREIGN KEY (`Depository_Module`)
    REFERENCES `Depository_Modules` (`Depository_Modules_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `Manager_id` INT NOT NULL,
  `managing` TINYINT NOT NULL,
  `Bank` INT NOT NULL,
  `Employee` INT NOT NULL,
  PRIMARY KEY (`Manager_id`),
  INDEX `FK_Manager_Bank_idx` (`Bank` ASC) VISIBLE,
  INDEX `FK_Manager_Employee_idx` (`Employee` ASC) VISIBLE,
  CONSTRAINT `FK_Manager_Bank`
    FOREIGN KEY (`Bank`)
    REFERENCES `Bank` (`Bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Manager_Employee`
    FOREIGN KEY (`Employee`)
    REFERENCES `Employee` (`Employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
